// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/split/DividasGrupo.tsx": () => import("../components/mockups/split/DividasGrupo.tsx"),
  "./components/mockups/split/NovaDespesa.tsx": () => import("../components/mockups/split/NovaDespesa.tsx"),
  "./components/mockups/split/ResumoGrupo.tsx": () => import("../components/mockups/split/ResumoGrupo.tsx")
};
